# ---------------------------------------------------------------------------
#
#         Developed by VertrauterDavid, remade by opmasterleo
#
#         https://vertrauterdavid.net/
#         https://github.com/Kaleshnikk
#
# ---------------------------------------------------------------------------

# Notify opped players about updates when they join the server
update-notify-chat: false

# Duration of the combat timer in seconds
Duration: 15

# Enable combat only in specific worlds
EnabledWorlds:
  enabled: false
  worlds:
    - world1
    - world2

Messages:
  Prefix: '' # Prefix for all messages
  NowInCombat: '' # empty = disabled
  NoLongerInCombat: '' # empty = disabled
  LogoutInCombat: '' # empty = disabled


CustomDeathMessage:
  enabled: false # Enables custom death messages
  prefix: '&c☠ '  

# Disable Combat for all with OP permissions
ignore-op: false

# Disable Elytra in combat
disable-elytra: false

# Settings for the action bar message during combat
ActionBar:
  Enabled: true # Enables the action bar message
  Format: '&#C7CEDCCombat: &#37bff9%seconds%s'

Commands:
  Blocked: # List of commands that are blocked during combat
    - spawn
    - tpa
    - tpahere
    - home
    - homes
    - rtp
    - afk 
    - warp
    - warps
  Format: '&7You cannot use &c%command% &7while in combat!'

EnderPearl:
  Enabled: false # Enables restrictions on ender pearl usage during combat
  Distance: 25 # Maximum allowed teleport distance with ender pearls
  Format: 'You cannot teleport that far away in combat!'
