name: ${project.name}
main: net.opmasterleo.combat.Combat
version: ${project.version}
api-version: 1.21
author: OPmasterLEO
description: ${project.description}
folia-supported: true
depend:
  - WorldGuard
commands:
  combat:
    description: Manage Combat plugin
    usage: /combat [reload|toggle|update]
    aliases: [combattoggle, combatreload, combatupdate]
