name: ${project.name}
main: net.opmasterleo.combat.Combat
version: ${project.version}
api-version: 1.21
author: OPmasterLEO
folia-supported: true
softdepend:
  - WorldGuard
commands:
  combat:
    description: Manage Combat plugin
    usage: /combat [reload|toggle]
    aliases: [combattoggle, combatreload]